### ISSUE TITLE
Remove the instruction in the readme to turn off do.parallel

### ISSUE THREAD

**Issue by Maylor8** [ShimmerEngineering/Verisense-Toolbox#4]
We tested this during our work and there was no difference in any of the outputs when do.parallel=TRUE, so this doesn't appear to be required.

**Comment by vincentvanhees** [comment]
@m-patterson @ShimmerEngineering or @marknolan could you please address this? It is just one line of text in the README that is causing a lot of confusion among end-users.

**Comment by ShimmerEngineering** [comment]
https://github.com/ShimmerEngineering/Verisense-Toolbox/blob/master/Verisense_step_algorithm/ReadMe.md this is updated now
